import{a as w,S,i as u}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();async function m(e,r=1,s=15){const a="https://pixabay.com",t="/api/",o=new URLSearchParams({key:"44168099-5911f69422da676ec159a331f",q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:s}),n=`${a}${t}?${o}`;try{return(await w(n)).data}catch(y){console.error(y.message)}}const $=document.querySelector(".gallery");let i;function g(e){const r=e.map(s=>q(s)).join("");$.insertAdjacentHTML("beforeend",r),i||(i=new S(".gallery a",{captionDelay:250,captionsData:"alt"})),i.refresh()}function q(e){return`
                <a class="link" href="${e.largeImageURL}" class="gallery-link">
                    <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
                <ul class="info">
                 <li><h3 class="info-title">Likes</h3><p class="info-text">${e.likes}</p></li>
                 <li><h3 class="info-title">Views</h3><p class="info-text">${e.views}</p></li>
                 <li><h3 class="info-title">Comments</h3><p class="info-text">${e.comments}</p></li>
                 <li><h3 class="info-title">Downloads</h3><p class="info-text">${e.downloads}</p></li>
                </ul>
                </a>
            `}function h(){const e=document.querySelector(".gallery");e.innerHTML=""}const v=document.querySelector(".search-form"),p=document.querySelector("input"),f=document.querySelector(".loader"),d=document.querySelector(".load-more"),x=document.querySelector(".gallery");function L(){f.style.display="block"}function b(){f.style.display="none"}let l=1,c="";v.addEventListener("submit",F);d.addEventListener("click",P);async function F(e){if(e.preventDefault(),c=p.value.trim(),c===""){h();return}l=1,L();try{const r=await m(c,l);r.hits.length===0?(h(),u.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",backgroundColor:"#EF4040",iconColor:"#FAFAFB",position:"topRight"}),p.value="",d.style.display="none"):(g(r.hits),d.style.display="flex",f.style.position="relative")}catch(r){u.error({title:"Error",message:r.message})}finally{b()}}async function P(){l+=1,L();try{const e=await m(c,l);g(e.hits);const{height:r}=x.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),e.totalHits<=l*15&&(d.style.display="none",u.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}))}catch(e){u.error({title:"Error",message:e.message})}finally{b()}}
//# sourceMappingURL=commonHelpers.js.map
