import{a as v,S,i as a}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function l(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=l(t);fetch(t.href,r)}})();async function g(e,o=1,l=15){const c="https://pixabay.com",t="/api/",r=new URLSearchParams({key:"44168099-5911f69422da676ec159a331f",q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:l}),n=`${c}${t}?${r}`;try{return(await v(n)).data}catch(h){console.error(h.message)}}const q=document.querySelector(".gallery");let u;function L(e){const o=e.map(l=>$(l)).join("");q.insertAdjacentHTML("beforeend",o),u||(u=new S(".gallery a",{captionDelay:250,captionsData:"alt"})),u.refresh()}function $(e){return`
                <a class="link" href="${e.largeImageURL}" class="gallery-link">
                    <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
                <ul class="info">
                 <li><h3 class="info-title">Likes</h3><p class="info-text">${e.likes}</p></li>
                 <li><h3 class="info-title">Views</h3><p class="info-text">${e.views}</p></li>
                 <li><h3 class="info-title">Comments</h3><p class="info-text">${e.comments}</p></li>
                 <li><h3 class="info-title">Downloads</h3><p class="info-text">${e.downloads}</p></li>
                </ul>
                </a>
            `}function f(){const e=document.querySelector(".gallery");e.innerHTML=""}const x=document.querySelector(".search-form"),m=document.querySelector("input"),p=document.querySelector(".loader"),i=document.querySelector(".load-more"),E=document.querySelector(".gallery"),d=document.querySelector(".scrollToTopBtn");function b(){p.style.display="block"}function w(){p.style.display="none"}function T(){window.scrollTo({top:0,behavior:"smooth"})}let s=1,y="";x.addEventListener("submit",F);i.addEventListener("click",P);d.addEventListener("click",T);async function F(e){if(e.preventDefault(),f(),y=m.value.trim(),y===""){f();return}s=1,b();try{const o=await g(y,s);o.hits.length===0?(f(),a.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",backgroundColor:"#EF4040",iconColor:"#FAFAFB",position:"topRight"}),m.value="",i.style.display="none",d.style.display="none"):(L(o.hits),i.style.display="flex",d.style.display="flex",p.style.position="relative",o.totalHits<=s*15&&(i.style.display="none",d.style.display="none",a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})))}catch(o){a.error({title:"Error",message:o.message})}finally{w()}}async function P(){s+=1,b();try{const e=await g(y,s);L(e.hits);const{height:o}=E.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),e.totalHits<=s*15&&(i.style.display="none",a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}))}catch(e){a.error({title:"Error",message:e.message})}finally{w()}}
//# sourceMappingURL=commonHelpers.js.map
