import{a as p,i as c,S as d}from"./assets/vendor-b0d10f48.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function y(t,o=1,s=15){const n="https://pixabay.com",e="/api/",r=new URLSearchParams({key:"44168099-5911f69422da676ec159a331f",q:`${t}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:s}),a=`${n}${e}?${r}`;try{const i=await p(a);return i.totalHits===0?(c.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",backgroundColor:"#EF4040",iconColor:"#FAFAFB",position:"topRight"}),[]):i.hits}catch(i){return console.error(i.message),c.error({message:"An error occurred while fetching images. Please try again later.",messageColor:"#FAFAFB",backgroundColor:"#EF4040",iconColor:"#FAFAFB",position:"topRight"}),[]}}const m=document.querySelector(".gallery");let l;function h(t){m.innerHTML=t.map(o=>g(o)).join(""),l||(l=new d(".gallery a",{captionDelay:250,captionsData:"alt"})),l.refresh()}function g(t){return`
                <a class="link" href="${t.largeImageURL}" class="gallery-link">
                    <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" />
                <ul class="info">
                 <li><h3 class="info-title">Likes</h3><p class="info-text">${t.likes}</p></li>
                 <li><h3 class="info-title">Views</h3><p class="info-text">${t.views}</p></li>
                 <li><h3 class="info-title">Comments</h3><p class="info-text">${t.comments}</p></li>
                 <li><h3 class="info-title">Downloads</h3><p class="info-text">${t.downloads}</p></li>
                </ul>
                </a>
            `}function F(){const t=document.querySelector(".gallery");t.innerHTML=""}const L=document.querySelector(".search-form"),u=document.querySelector("input"),f=document.querySelector(".loader");function b(){f.style.display="block"}function w(){f.style.display="none"}L.addEventListener("submit",t=>{t.preventDefault();const o=u.value.trim();if(o===""){F();return}b();try{const s=y(o);h(s),u.value=""}catch(s){c.error({title:"Error",message:s.message})}finally{w()}});
//# sourceMappingURL=commonHelpers.js.map
